version: '3.3'
services:
# Python Flask (Front-End / API)
  app:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./app.py:/app/app.py  # Mapeia o arquivo app.py externo
      - ./templates:/app/templates  # Mapeia o diretório de templates
      - ./static:/app/static  # Mapeia o diretório de arquivos estáticos
    depends_on:
      - redis

# Celery Worker (Back-End)
  celery_worker:
    build: .
    command: celery -A app.celery worker --loglevel=info
    volumes:
      - .:/app
    depends_on:
      - redis

# Celery GUI (Management)
  flower:
    image: mher/flower
    command: flower --broker=redis://redis:6379/0 --port=5555
    ports:
      - "5555:5555"
    depends_on:
      - redis

# Redis DB
  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"

# Redis GUI
  redis-commander:
    image: rediscommander/redis-commander:latest
    environment:
      - REDIS_HOSTS=local:redis:6379
    ports:
      - "8081:8081"
    depends_on: 
      - redis