version: '3.3'

services:
  jupyter-spark:
    build: .
    ports:
      - "8888:8888"
      - "4040:4040"  # Porta padrão da interface web do Spark
    volumes:
      - ./notebooks:/home/jovyan/work
      - ./data:/data
